"use client";
import {Search,Globe2,Wifi,ShieldCheck,Headphones,ArrowRight,UserRound,Menu,CheckCircle2,ChevronLeft,X,QrCode,Plane} from "lucide-react";
import {useMemo,useState} from "react";

const featured=[
["🇹🇷","Türkiye","Avrupa","İstanbul","4,50 €"],["🇮🇹","İtalya","Avrupa","Roma","4,50 €"],["🇫🇷","Fransa","Avrupa","Paris","4,50 €"],["🇪🇸","İspanya","Avrupa","Barselona","4,50 €"],
["🇺🇸","ABD","Kuzey Amerika","New York","5,00 €"],["🇬🇧","İngiltere","Avrupa","Londra","4,00 €"],["🇩🇪","Almanya","Avrupa","Berlin","4,50 €"],["🇬🇷","Yunanistan","Avrupa","Santorini","4,50 €"],
["🇯🇵","Japonya","Asya","Tokyo","5,50 €"],["🇹🇭","Tayland","Asya","Bangkok","4,90 €"],["🇦🇪","BAE","Orta Doğu","Dubai","5,50 €"],["🇸🇦","Suudi Arabistan","Orta Doğu","Riyad","5,50 €"]
];
const extraNames=["Arnavutluk","Andorra","Avusturya","Belçika","Bulgaristan","Hırvatistan","Kıbrıs","Çekya","Danimarka","Estonya","Finlandiya","Macaristan","İzlanda","İrlanda","Letonya","Litvanya","Lüksemburg","Malta","Hollanda","Norveç","Polonya","Portekiz","Romanya","Sırbistan","Slovakya","Slovenya","İsveç","İsviçre","Kanada","Meksika","Brezilya","Arjantin","Şili","Kolombiya","Peru","Uruguay","Çin","Güney Kore","Singapur","Malezya","Endonezya","Filipinler","Vietnam","Hindistan","Pakistan","Katar","Kuveyt","Umman","Ürdün","İsrail","Mısır","Fas","Tunus","Güney Afrika","Kenya","Tanzanya","Nijerya","Gana","Avustralya","Yeni Zelanda","Fiji"];
const extras=extraNames.map((n,i)=>["🌐",n, i<28?"Avrupa":i<34?"Kuzey Amerika":i<39?"Güney Amerika":i<48?"Asya":i<54?"Orta Doğu":i<59?"Afrika":"Okyanusya","NordicConnect","4,90 €"]);
const countries=[...featured,...extras];
const regions=["Tümü","Avrupa","Asya","Kuzey Amerika","Güney Amerika","Afrika","Orta Doğu","Okyanusya"];
const plans=[["1 GB","7 Gün","4,50 €"],["3 GB","15 Gün","8,00 €"],["5 GB","30 Gün","12,00 €"],["10 GB","30 Gün","18,00 €"],["20 GB","30 Gün","28,00 €"]];

export default function Home(){
 const [screen,setScreen]=useState("home"),[q,setQ]=useState(""),[region,setRegion]=useState("Tümü"),[selected,setSelected]=useState(featured[0]),[plan,setPlan]=useState(plans[2]),[qr,setQr]=useState(false);
 const go=(s:string)=>{setScreen(s);window.scrollTo({top:0,behavior:"smooth"})};
 const shown=useMemo(()=>countries.filter(c=>(region==="Tümü"||c[2]===region)&&c[1].toLowerCase().includes(q.toLowerCase())),[q,region]);
 const choose=(c:any)=>{setSelected(c);go("detail")};
 return <main>
 <header><button className="brand plain" onClick={()=>go("home")}><span className="mark">N</span><b>NordicConnect</b></button><nav><button onClick={()=>go("countries")}>eSIM'ler</button><a href="#how">Nasıl Çalışır?</a><a href="#support">Destek</a></nav><div className="actions"><button className="ghost"><Search/></button><button className="ghost"><Globe2/> TR · EUR</button><button className="login" onClick={()=>go("account")}><UserRound/> Hesabım</button><button className="mobile"><Menu/></button></div></header>

 {screen==="home"&&<><section className="hero"><div className="heroInner reveal"><span className="eyebrow">GLOBAL eSIM · ANINDA TESLİMAT</span><h1>Dünyanın her yerinde<br/><em>bağlantıda kalın.</em></h1><p>Seyahatlerinizde hızlı, güvenilir ve uygun fiyatlı eSIM çözümleri. Fiziksel SIM yok, roaming sürprizi yok.</p><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nereye seyahat ediyorsunuz?"/><button onClick={()=>go("countries")}>Ara <ArrowRight/></button></div><div className="trust"><span>✓ Anında aktivasyon</span><span>✓ Fiziksel SIM gerekmez</span><span>✓ 7/24 destek</span></div></div>
 <div className="destinationArt"><div className="orbit"/><Plane className="plane"/><div className="landscape">SANTORINI</div><div className="cardFloat"><div><span>🇹🇷</span><b>Türkiye</b><i>● Aktif</i></div><small>10 GB · 30 Gün</small><div className="usageMini"><strong>72%</strong><div><span>Kalan Veri</span><b>7.2 GB</b></div></div></div></div></section>
 <section className="section"><div className="heading"><div><span className="eyebrow dark">POPÜLER ÜLKELER</span><h2>Nereye gidiyorsunuz?</h2></div><button className="linkBtn" onClick={()=>go("countries")}>200+ destinasyonu keşfet <ArrowRight/></button></div><div className="photoGrid">{featured.slice(0,8).map((c,i)=><button className="photoCountry" style={{animationDelay:`${i*.06}s`}} key={c[1]} onClick={()=>choose(c)}><div className={"countryPhoto p"+i}><span>{c[3]}</span></div><div className="countryMeta"><span className="bigFlag">{c[0]}</span><div><b>{c[1]}</b><small>{c[4]}'dan</small></div><ArrowRight/></div></button>)}</div></section>
 <section className="why section"><h2>Neden NordicConnect?</h2><div className="features"><Feature icon={<Wifi/>} t="Anında Kurulum" p="Dakikalar içinde eSIM'iniz hazır."/><Feature icon={<ShieldCheck/>} t="Güvenli Ödeme" p="Şeffaf fiyatlar ve güvenli ödeme."/><Feature icon={<Globe2/>} t="200+ Destinasyon" p="Dünyanın dört bir yanında bağlantı."/><Feature icon={<Headphones/>} t="7/24 Destek" p="Her zaman yanınızdayız."/></div></section>
 <section id="how" className="how"><div className="wave"/><div className="section"><span className="eyebrow">3 KOLAY ADIM</span><h2>Nasıl çalışır?</h2><div className="steps"><Step n="1" t="Destinasyonunu seç" p="Gideceğin ülkeyi ve paketini belirle."/><Step n="2" t="Güvenle satın al" p="Ödemeni tamamla, eSIM'ini anında al."/><Step n="3" t="QR kodu tara" p="Telefonuna kur ve hemen kullanmaya başla."/></div></div></section></>}

 {screen==="countries"&&<div className="page section reveal"><Back go={()=>go("home")}/><h1 className="pageTitle">Popüler Ülkeler</h1><p className="sub">200+ destinasyon için eSIM paketlerini keşfedin.</p><div className="filterBar"><div className="tabs">{regions.map(r=><button className={region===r?"active":""} onClick={()=>setRegion(r)} key={r}>{r}</button>)}</div><div className="countrySearch"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ülke ara..."/></div></div><div className="photoGrid all">{shown.map((c,i)=><button className="photoCountry" key={c[1]} onClick={()=>choose(c)}><div className={"countryPhoto p"+(i%8)}><span>{c[3]}</span></div><div className="countryMeta"><span className="bigFlag">{c[0]}</span><div><b>{c[1]}</b><small>{c[4]}'dan</small></div><ArrowRight/></div></button>)}</div></div>}

 {screen==="detail"&&<div className="page section reveal"><Back go={()=>go("countries")}/><div className="destinationDetail"><div className="destinationHero"><div className="detailScene"><span>{selected[3]}</span></div><div className="thumbs"><i/><i/><i/><i/></div></div><div className="packageSide"><div className="titleRow"><span className="bigFlag">{selected[0]}</span><div><h1>{selected[1]}</h1><p>★★★★★ <small>4.8 · 2.548 değerlendirme</small></p></div><span className="status">● Popüler</span></div><div className="packageTabs"><b>Veri Paketleri</b><span>Detaylar</span><span>Uyumluluk</span><span>Yorumlar</span></div><div className="plans">{plans.map((p,i)=><button className={plan===p?"selected":""} key={p[0]} onClick={()=>setPlan(p)}><span>＋</span><div><b>{p[0]}</b><small>{p[1]}</small></div>{i===2&&<i>En Popüler</i>}<strong>{p[2]}</strong><em onClick={()=>go("checkout")}>Seç</em></button>)}</div></div></div></div>}

 {screen==="checkout"&&<div className="page narrow reveal"><Back go={()=>go("detail")}/><h2>Güvenli Ödeme</h2><div className="checkoutCard"><div className="order"><span>{selected[0]}</span><div><b>{selected[1]} {plan[0]}</b><small>{plan[1]} · 4G/5G</small></div><strong>{plan[2]}</strong></div><label>Kart Üzerindeki İsim<input placeholder="Ad Soyad"/></label><label>Kart Numarası<input placeholder="1234 5678 9012 3456"/></label><div className="two"><label>Son Kullanma<input placeholder="12 / 28"/></label><label>CVV<input placeholder="•••"/></label></div><div className="total"><span>Toplam</span><strong>{plan[2]}</strong></div><button className="primary" onClick={()=>go("success")}>Ödemeyi Tamamla</button></div></div>}

 {screen==="success"&&<div className="page narrow success reveal"><div className="successPulse"><CheckCircle2/></div><h1>eSIM'iniz aktif!</h1><p>Artık seyahatinizde bağlantıdasınız.</p><button className="primary" onClick={()=>go("account")}>eSIM'lerime Git</button><button className="linkBtn centerBtn" onClick={()=>go("countries")}>Yeni Paket Satın Al</button></div>}

 {screen==="account"&&<div className="account page reveal"><aside><h3>Hesabım</h3>{["eSIM'lerim","Siparişlerim","Profil Bilgilerim","Ödeme Yöntemleri","Destek Talepleri","Çıkış Yap"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</aside><section><h1>eSIM'lerim</h1><div className="accountTabs"><b>Aktif</b><span>Yaklaşan</span><span>Geçmiş</span></div><div className="simCard"><div className="simTop"><span className="bigFlag">🇹🇷</span><div><h2>Türkiye 10 GB</h2><p>Türk Telekom · 10 GB / 30 Gün</p></div><span className="status">● Aktif</span></div><div className="usage"><div className="ring">72%</div><div><small>Kalan Veri</small><b>7.2 GB</b><small>/ 10 GB</small></div></div><button className="primary" onClick={()=>setQr(true)}><QrCode/> QR Kodu Görüntüle</button></div></section></div>}
 {qr&&<div className="modal" onClick={()=>setQr(false)}><div className="qrModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setQr(false)}><X/></button><h3>eSIM Kurulumu</h3><p>QR kodu telefonunuzla tarayın</p><div className="fakeQr">{Array.from({length:81}).map((_,i)=><i className={(i*7+i%5)%3===0?"on":""} key={i}/>)}</div><button className="outline">Talimatları Göster</button></div></div>}
 <footer id="support"><div className="brand"><span className="mark">N</span><b>NordicConnect</b></div><p>Dünyanın her yerinde kolay ve güvenilir bağlantı.</p><small>© 2026 NordicConnect</small></footer></main>
}
function Feature({icon,t,p}:any){return <article>{icon}<b>{t}</b><p>{p}</p></article>}
function Step({n,t,p}:any){return <div><i>{n}</i><Wifi/><h3>{t}</h3><p>{p}</p></div>}
function Back({go}:any){return <button className="back" onClick={go}><ChevronLeft/> Geri</button>}
