'use client';
import Link from 'next/link';
import {Search,Globe2,UserRound,ChevronDown,ArrowRight,MapPin,Plane,MessageCircle} from 'lucide-react';
import {useState} from 'react';
export const destinations=[['Türkiye','Istanbul','TR','4.00','photo-1524231757912-21f4fe3a7200'],['Japonya','Tokyo','JP','4.00','photo-1540959733332-eab4deabeeaf'],['İtalya','Rome','IT','4.00','photo-1529260830199-42c24126f198'],['ABD','New York','US','4.00','photo-1485871981521-5b1fd3805eee'],['İspanya','Barcelona','ES','4.00','photo-1539037116277-4db20889f2d4'],['Fransa','Paris','FR','4.00','photo-1502602898657-3e91760cbb34'],['İngiltere','London','GB','4.00','photo-1513635269975-59663e0ac1ad'],['BAE','Dubai','AE','5.00','photo-1512453979798-5ea266f8880c']];
export const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=86`;
export const flag=(c:string)=>`https://flagcdn.com/w80/${c.toLowerCase()}.png`;
export function Shell({children}:{children:React.ReactNode}){const [menu,setMenu]=useState(false);return <><div className="topbar">Yeni: 130+ destinasyonda sınırsız veri seçenekleri <Link href="/esim">Keşfet →</Link></div><header><Link href="/" className="brand"><span>N</span><b>NordicConnect</b></Link><nav><div className="navdrop"><button onClick={()=>setMenu(!menu)}>eSIM Mağazası <ChevronDown/></button>{menu&&<div className="mega"><Link href="/local-esim"><MapPin/>Yerel eSIM<small>Tek ülke için</small></Link><Link href="/regional-esim"><Plane/>Bölgesel eSIM<small>Birden fazla ülke</small></Link><Link href="/global-esim"><Globe2/>Global eSIM<small>Dünya çapında</small></Link></div>}</div><Link href="/how-it-works">Nasıl çalışır?</Link><Link href="/about-esim">eSIM nedir?</Link><Link href="/business">Kurumsal</Link><Link href="/help">Yardım</Link></nav><div className="headerActions"><Link href="/esim" className="icon"><Search/></Link><button className="locale"><Globe2/> TR · EUR <ChevronDown/></button><Link href="/login" className="account"><UserRound/> Giriş yap</Link></div></header>{children}<button className="chat"><MessageCircle/><span>Canlı destek</span></button><Footer/></>}
export function Footer(){return <footer><div><Link href="/" className="brand light"><span>N</span><b>NordicConnect</b></Link><p>Yolculuğunuz nerede olursa olsun, bağlantınız hazır.</p></div><div><b>eSIM'ler</b><Link href="/local-esim">Yerel</Link><Link href="/regional-esim">Bölgesel</Link><Link href="/global-esim">Global</Link></div><div><b>Öğren</b><Link href="/how-it-works">Nasıl çalışır?</Link><Link href="/about-esim">eSIM nedir?</Link><Link href="/help">Yardım merkezi</Link></div><div><b>NordicConnect</b><Link href="/business">Kurumsal çözümler</Link><span>Gizlilik</span><span>Koşullar</span></div><div className="footBottom">© 2026 NordicConnect <span>Visa · Mastercard · Apple Pay · Google Pay</span></div></footer>}
export function DestinationCard({d}:{d:string[]}){return <Link href="/country/turkey" className="dest"><div className="destImg"><img alt="" src={img(d[4])}/><span>4G / 5G</span></div><div className="destBody"><img alt="" src={flag(d[2])}/><div><b>{d[0]}</b><small>€{d[3]}'dan başlayan</small></div><ArrowRight/></div></Link>}
export function SearchHero(){return <div className="searchHero"><Search/><input placeholder="Nereye seyahat ediyorsunuz?"/><Link href="/esim">eSIM ara <ArrowRight/></Link></div>}
export function Store({title='eSIM Mağazası',active='all'}:{title?:string,active?:string}){return <main className="page"><section className="storeHead"><span className="eyebrow">NORDICCONNECT eSIM STORE</span><h1>{title}</h1><p>Destinasyonunu seç, paketini karşılaştır ve birkaç dakika içinde bağlan.</p><SearchHero/></section><div className="storeTabs"><Link className={active==='all'?'on':''} href="/esim">Tümü</Link><Link className={active==='local'?'on':''} href="/local-esim">Yerel</Link><Link className={active==='regional'?'on':''} href="/regional-esim">Bölgesel</Link><Link className={active==='global'?'on':''} href="/global-esim">Global</Link></div>{active==='regional'?<Regions/>:active==='global'?<Global/>:<div className="destGrid">{destinations.map(d=><DestinationCard d={d} key={d[0]}/>)}</div>}</main>}
function Regions(){return <div className="regionGrid">{[['Avrupa','42 ülke','€5'],['Asya','18 ülke','€6'],['Kuzey Amerika','3 ülke','€7'],['Orta Doğu & Kuzey Afrika','13 ülke','€8'],['Latin Amerika','19 ülke','€9'],['Okyanusya','8 ülke','€7']].map(x=><Link href="/country/turkey" key={x[0]}><Globe2/><div><b>{x[0]}</b><small>{x[1]}</small></div><strong>{x[2]}+</strong></Link>)}</div>}
function Global(){return <section className="globalPanel"><Globe2/><div><span className="eyebrow">GLOBAL COVERAGE</span><h2>Tek eSIM. Birçok ülke.</h2><p>130+ ülkede çalışan global paketlerle sınır geçerken SIM değiştirmeyin.</p><Link className="primary" href="/country/turkey">Global paketleri gör <ArrowRight/></Link></div></section>}